services:
  backend:
    user: root
    build:
      context: ./backend
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./.env:/app/.env # for google auth credentials
    command: >
      sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    build:
      context: ./nginx
    platform: linux/amd64
    volumes:
      - backend:/backend
      - ./frontend/dist:/var/www/frontend # for production
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:13-alpine
    volumes:
      #- dev-db-data:/var/lib/postgresql/data
      - ./data:/var/lib/postgresql/data
    ports:
      # 54320 is likely unused on your local; to
      # support access through db-tools: dbeaver
      # https://stackoverflow.com/a/73870873
      - "54320:5432"
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  backend:
  frontend:
  pgadmin_data:
