version: "3.8"

services:
  backend:
    build:
      context: ./backend
    env_file: .env.test
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py test"

  db:
    image: postgres:13-alpine
    env_file: .env.test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "testuser", "-d", "testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
