# Generated by Django 4.2.19 on 2025-03-10 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_project_target"),
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="project.project",
            ),
        ),
    ]
