# Generated by Django 4.2.19 on 2025-04-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campaign',
            name='img',
            field=models.ImageField(blank=True, help_text='Optional main image representing the campaign.', null=True, upload_to='campaigns/'),
        ),
    ]
