# Generated by Django 4.2.19 on 2025-02-24 21:27

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="target",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="USD",
                help_text="Financial target (money) the project aims to raise.",
                max_digits=14,
                validators=[
                    djmoney.models.validators.MinMoneyValidator({"USD": 0.01})
                ],
            ),
        ),
    ]
