# Generated by Django 4.2.19 on 2025-04-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the project.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('funded', 'Funded'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', help_text='Status of project, default is DRAFT.', max_length=50),
        ),
    ]
