# Generated by Django 4.2.19 on 2025-05-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_cause_created_cause_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cause',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
    ]
