# Generated by Django 4.2.19 on 2025-02-22 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_phone_number_alter_usergroup_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_account_token_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("PENDING", "Pending"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("last_payout", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="bank_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="bank_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.bankaccount",
            ),
        ),
    ]
