name: Django Tests (Docker)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: devdb
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: changeme
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U devuser -d devdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Run migrations
        run: docker compose run --rm backend sh -c "python manage.py migrate"

      - name: Run tests
        run: docker compose run --rm backend sh -c "python manage.py test"

      - name: Stop and clean up
        run: docker compose down
